repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--settings-file=setup.cfg"]
        files: ^backend/

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^backend/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        files: ^backend/

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        name: black (data-engineering)
        files: ^data-engineering/

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        name: black (qa)
        files: ^qa/

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, test, chore, devops, refactor, ci]
